-- Seed data for the House of Charity Supabase project.
-- Run this after `supabase_schema.sql` to populate initial NGOs (and sample requirements).

-- Example NGO records. Password hashes are bcrypt (cost 10) for demonstration passwords noted below.
insert into public.ngos (
  id,
  name,
  email,
  password_hash,
  phone_number,
  address,
  city,
  state,
  country,
  pincode,
  works_done,
  awards_received,
  about,
  gallery,
  current_requirements,
  future_plans,
  awards_and_recognition,
  recent_activities,
  description,
  website,
  logo_url,
  verified,
  created_at,
  updated_at
) values
  -- Password: cuddles
  (
    gen_random_uuid(),
    'Cuddles Foundation',
    'team@cuddlesfoundation.com',
    crypt('cuddles', gen_salt('bf')),
    '+91-9604269875',
    '402, Orchid Apartments, Bandra West',
    'Mumbai',
    'Maharashtra',
    'India',
    '400050',
    'Nutrition programs for pediatric cancer patients|Partnered with 35 hospitals|Trained 120 nutritionists',
    'National Award for Child Welfare 2022|Healthcare Excellence Award 2021',
    null,
    null,
    null,
    null,
    null,
    null,
    'Ensuring children fighting cancer have access to nutrition and holistic care.',
    'https://www.cuddlesfoundation.com',
    'https://assets.example.org/logos/cuddles.png',
    true,
    now(),
    now()
  ),
  -- Password: green
  (
    gen_random_uuid(),
    'Green Earth Initiative',
    'hello@greenearth.org',
    crypt('green', gen_salt('bf')),
    '+91-9876543210',
    'Plot 28, Eco Towers, HSR Layout',
    'Bengaluru',
    'Karnataka',
    'India',
    '560102',
    'Planted 50,000 native saplings|Built community composting units|Created urban micro-forests',
    'UN Climate Action Recognition 2023',
    null,
    null,
    null,
    null,
    null,
    null,
    'Driving community-led climate action with afforestation and waste management.',
    'https://www.greenearth.org',
    'https://assets.example.org/logos/green-earth.png',
    true,
    now(),
    now()
  ),
  -- Password: hope
  (
    gen_random_uuid(),
    'Hope Haven Shelter',
    'connect@hopehaven.org',
    crypt('hope', gen_salt('bf')),
    '+91-9876504321',
    '12, Shelter Lane, Adyar',
    'Chennai',
    'Tamil Nadu',
    'India',
    '600020',
    'Rehabilitated 1,200 women and children|Skill development & education programs|Emergency relief camps',
    'State Humanitarian Award 2020',
    null,
    null,
    null,
    null,
    null,
    null,
    'Safe housing, education, and rehabilitation for women and children escaping abuse.',
    'https://www.hopehaven.org',
    'https://assets.example.org/logos/hope-haven.png',
    false,
    now(),
    now()
  )
on conflict (email) do update
set
  name = excluded.name,
  password_hash = excluded.password_hash,
  phone_number = excluded.phone_number,
  address = excluded.address,
  city = excluded.city,
  state = excluded.state,
  country = excluded.country,
  pincode = excluded.pincode,
  works_done = excluded.works_done,
  awards_received = excluded.awards_received,
  about = excluded.about,
  gallery = excluded.gallery,
  current_requirements = excluded.current_requirements,
  future_plans = excluded.future_plans,
  awards_and_recognition = excluded.awards_and_recognition,
  recent_activities = excluded.recent_activities,
  description = excluded.description,
  website = excluded.website,
  logo_url = excluded.logo_url,
  verified = excluded.verified,
  updated_at = now();

-- Example donor records.
-- Sample requirements linked to the NGOs above.
insert into public.requirements (
  id,
  ngo_id,
  request_type,
  category,
  details,
  amount_needed,
  currency,
  quantity,
  unit,
  priority,
  status,
  created_at,
  updated_at
) values
  (
    gen_random_uuid(),
    (select id from public.ngos where name = 'Cuddles Foundation' limit 1),
    'money',
    'Healthcare',
    'Monthly nutrition kits for pediatric cancer patients.',
    250000,
    'INR',
    null,
    null,
    'high',
    'active',
    now(),
    now()
  ),
  (
    gen_random_uuid(),
    (select id from public.ngos where name = 'Green Earth Initiative' limit 1),
    'money',
    'Environment',
    'Community sapling drive across five wards, including caretaker training.',
    180000,
    'INR',
    null,
    null,
    'medium',
    'active',
    now(),
    now()
  ),
  (
    gen_random_uuid(),
    (select id from public.ngos where name = 'Hope Haven Shelter' limit 1),
    'daily_essentials',
    'Shelter',
    'Emergency hygiene kits and bedding for new residents.',
    null,
    'INR',
    150,
    'kits',
    'urgent',
    'active',
    now(),
    now()
  );

